Integrate tests to CI (#28)
* Test CI

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -167,7 +167,7 @@ jobs:
   build-docs:
     needs: linux
     runs-on: ubuntu-latest
-    if: "startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'"
+    if: "startsWith(github.ref, 'refs/tags/') || (github.ref == 'main' && github.event_name == 'workflow_dispatch')"
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-python@v4
@@ -217,6 +217,34 @@ jobs:
         id: deployment
         uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
 
-
+  tests:
+    needs: linux
+    strategy:
+      matrix:
+        python-version: ["3.8", "3.9", "3.10", "3.11"]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - uses: actions/download-artifact@v4
+        with:
+          name: wheels-linux-x86_64
+          path: wheels/
+      - name: "Install packages"
+        run: |
+          python -m pip install --upgrade pip
+          pip install pytest wheels/*.whl
+      - name: Test with pytest
+        run: pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml test/
+      - name: Upload pytest test results
+        uses: actions/upload-artifact@v4
+        with:
+          name: pytest-results-${{ matrix.python-version }}
+          path: junit/test-results-${{ matrix.python-version }}.xml
+        # Use always() to always run this step to publish test results when there are test failures
+        if: ${{ always() }}
 
 
